modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="bloomanddoom" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Bloom and Doom" #mandatory
logoFile="examplemod.png" #optional
credits="Ninni and Zae" #optional
authors="Wadoo" #optional
description='''
Plant vs Zombies inspired mod'''

[[dependencies.bloomanddoom]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.bloomanddoom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"